### PR TITLE
Missing images + extra tabs

### PR DESCRIPTION
**Pull request by pjmikkol**
Added the images that I noticed were missing. Also added a tab for Prizes and 'fixed' additional rules tab for Possession.

### CODE REVIEW

**Comment by nickv2002** [comment]
Awesome.  Thanks for all the edits and new images.  Hope they get merged soon an put up on the web so I can integrate them into my print outs.

**Comment by sumpfork** [comment]
This is online now.

**Comment by nickv2002** [comment]
Sweet, thanks @sumpfork and @pjmikkol

**Comment by pjmikkol** [comment]
Nice. And thanks for awesome tabs!

**Comment by pjmikkol** [comment]
Hi. I noticed wrong image in reaction shelter (wrong image). It is now fixed in my master branch.

**Pull request merged**
