### PR TITLE
Dutch translations for Menagerie

### PR DESCRIPTION
**Pull request by maksler**

### CODE REVIEW

**Comment by sumpfork** [comment]
Looks good, but in fixing the travis build I seem to have broken the automatic check-in of the packaged language files somehow. I'll try to fix it on the weekend if I find the time, or you could run `doit update_languages` after installing the `doit` python package for now and check in the result into this branch. Thanks!

**Comment by maksler** [comment]
Hi Peter,

I've tried, but still I receive the following error when running doit update_languages:
```
[...]\Documents\git\dominiontabs>doit update_languages  
ERROR: Two different tasks can't have a common target.'src/domdiv/card_db\' is a target for update_languages and update_languages.
```

I've upgraded the doit package and recloned the repository, but to no avail... Any thoughts?

**Comment by sumpfork** [comment]
Could you try merging the latest master into this? I switched the card db compilation to use github actions and hopefully fixed it in the process...

**Comment by maksler** [comment]
Done, but the `doit update_languages` command still returns the same error. Was I supposed to run that again?

**Comment by sumpfork** [comment]
No, you can see above that the script checked in the generated card database in the package. Should be all good now - I'll check it over later and land it.

**Comment by sumpfork** [comment]
Note that the github action https://github.com/sumpfork/dominiontabs/blob/master/.github/workflows/compile_card_db.yml just does:
```
          pip install -r requirements.txt
          pip install .
          doit update_languages
```
Still not sure why that wouldn't work for you. Do you have any other local changes? What do `git diff` and `git status` show?

**Comment by maksler** [comment]
I've tried running the three lines manually. The first two lines work and still, `doit update_languages` returns the same error.

See below for the output of `git diff` and `git status`.

```
[...]\Documents\git\dominiontabs>git diff

[...]\Documents\git\dominiontabs>git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .doit.db.dat
        .doit.db.dir

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by nao237854** [comment]
@maksler I also had this problem, I suppose that @sumpfork forgot add recognizing the folder separator when splitting and joining translation filenames. This fix should work:

https://github.com/nao237854/dominiontabs/commit/744d83e6d413f41aa8daf8e688e03e5d10586b1f

**Pull request merged**
