### PR TITLE
Update German Translations and few other Fixes

### PR DESCRIPTION
**Pull request by SebastianHira**
Not sure if the change in README is correct. Only worked with _ for me. If you dont want it, just leave it. The rest is fine

### CODE REVIEW

**Comment by sumpfork** [comment]
Thanks for doing this! 

There's a non-standard field: `AssertionError: invalid extra field names for Grey Mustang (de): {'notes'}`

Also, it's definitely `pre-commit` as a command, so could you change that back?

`Amphore`: `Entweder jetzt oder zu Beginn deine nächsten Zuges:<br>+1 Kauf and +3 Coin.` sollte wahrscheinlich `deines` anstatt `deine` sein.

**Review by sumpfork — CHANGES_REQUESTED** [review]
Thanks for doing this!

There's an error in updating the language: `invalid extra field names for Grey Mustang (de): {'notes'}` - seems like an extra field name we're not currently accepting.

`Amphore`: `Entweder jetzt oder zu Beginn deine nächsten Zuges:<br>+1 Kauf and +3 Coin.`, `deine` sollte wahrscheinlich `deines` sein.

Also, it's definitely `pre-commit` so can you please change that back?

**Comment by SebastianHira** [comment]
Working on it. Notes apparently only works in english then. Will remove.

**Comment by SebastianHira** [comment]
I'm not sure if I did this correct now. If not, I can try reset head and do it again. Took me the past 2 hours to find out how to change the commit (and I am quite honestly now sure how this worked now as ive mostly just copy pasted random commands from the internet until something worked)

**Pull request closed without merging**
