### PR TITLE
Run language tool for #266

### PR DESCRIPTION
**Pull request by sumpfork**

### CODE REVIEW

**Comment by sumpfork** [comment]
Replaces #266

**Comment by beorn7** [comment]
Thank you very much for this. Would it be possible to tag a release with this included so that the German Renaissance cards are available on http://sandflea.org/?
Thanks again…

**Comment by sumpfork** [comment]
Aber sicher doch, v3.8.1 ist jetzt online.

**Comment by beorn7** [comment]
\o/

**Pull request merged**
