### PR TITLE
Add nl_NL translations for Plunder expansion

### PR DESCRIPTION
**Pull request by siblingsofthevoid**
Help, I think i just lost my sanity...

In all seriousness, these are all card descriptions and extras as per Dutch cards and manual.
In basically all cases i tried to preserve the order as it is in the en_US translations.

### CODE REVIEW

**Comment by siblingsofthevoid** [comment]
Yeah, can do that. I'll probably do it now, if that seems to not have happened, It'll be there in the evening ^^

**Comment by sumpfork** [comment]
Seems to have some missing tags now: `paragraph text '<para>Handel de geldkaartaf voordat je Landingstroepen op je trekstapel legt. Het is ok\xe9 als de geldkaart meerdere soorten heeft, inclusief Actie (zoals Toverrol).<br /><i><b>Voorbeeld:<b> is de geldkaart een Beeldje dan trek je 2 kaarten voordat je Landingstroepen op je Trekstapel legt.<i></para>' caused exception Parse error: saw </para> instead of expected </i>`

**Comment by siblingsofthevoid** [comment]
OH
that may actually be a typo on my side. Seems i missed one.
I'll do another full check for typos and unclosed tags ^^

**Comment by siblingsofthevoid** [comment]
Okay, I just did an entire pass over the diff and fixed as many typos and unclosed tags as i could find.

**Comment by sumpfork** [comment]
Remember you can run tests locally via `doit test` or `pip install -e .[dev]` and then `pytest`. Or, `tox` works too if you have that installed.

You'll also need to recompile the gzs and mark the conflict as resolved.

**Comment by siblingsofthevoid** [comment]
> You'll also need to recompile the gzs and mark the conflict as resolved.

Ah yes, forgive me, it's been a while since I've done dev stuff xD

**Comment by siblingsofthevoid** [comment]
Okay, I rebased on the latest master, I recompiled the card DB one last time (merged into 24795fe since i was rebasing anyway) and i ran the tests locally. Pytest does not seem to be complaining.

A note on marking the conflicts as resolved: I don't have write access to this repo, so i cannot mark conflicts as resolved ^^
The Card DB is in the latest state it could possibly be tho, so it should be fine.

**Comment by sumpfork** [comment]
Replaced by #541

**Pull request closed without merging**
