### PR TITLE
Dutch translation for Allies

### PR DESCRIPTION
**Pull request by Antheii**
Dutch translation for Allies, hope I did correctly with those new gzip files

### CODE REVIEW

**Comment by sumpfork** [comment]
Hi, thanks for contributing! Can you also check in the plain JSON files in the `card_db_src` folder that you (presumably) used to make these `gz` versions? The ones in the package you're checking in will just get erased if the changes aren't in the source files.

**Comment by Antheii** [comment]
Hi Peter,

Done (I hope.... still struggling with this Github push/pull thingy; 
doesn't help when you only use it once every two years or so when 
updating a translation here 🤣).

Regards, Hans

On 07-01-2023 22:44, Peter Gorniak wrote:

> Hi, thanks for contributing! Can you also check in the plain JSON files 
> in the card_db_src folder that you (presumably) used to make these gz 
> versions? The ones in the package you're checking in will just get 
> erased if the changes aren't in the source files.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/sumpfork/dominiontabs/pull/441#issuecomment-1374622861
[2]

**Comment by sumpfork** [comment]
I ran pre-commit (please read the README and install it in your checkout) and re-ran the card db compilation (it's out of date on this PR). Result is #448.

I'm also finding it hard to review the PR because a lot of the card entries moved around so they don't line up in the diff and I can't tell what got added/removed/translated/moved. I might enforce alphabetical sorting in the future, see #447.

That said, from spot checking the PDF looks good and I don't want to make translation work unduly difficult. I'm attaching a PDF here, could you check it?
[dominion_dividers.pdf](https://github.com/sumpfork/dominiontabs/files/10369911/dominion_dividers.pdf)

**Comment by Antheii** [comment]
Checked Allies more in detail, skimmed only through the rest, but all 
seems good to me.

Thanks!

> Looks fine to Message ID: 
> ***@***.***>

**Comment by sumpfork** [comment]
Replaced by #448

**Pull request closed without merging**
