### PR TITLE
Add Cornucopia and Guilds second edition and upgrade pack.

### PR DESCRIPTION
**Pull request by dbgalur**

### CODE REVIEW

**Comment by sumpfork** [comment]
Thanks! I'll try to find time to have a stab at trying it out this weekend. Probably just needs some minor formatting cleanup (`pip install pre-commit` would do cause this to be done when you `git commit`) so the linters are happy.

**Comment by dbgalur** [comment]
I'm trying to debug an issue where the Tournament and Rewards are not showing up as a group if I try to output the "cornucopiaAndGuilds2ndEdition" expansion with "--special-card-groups". (If I output "cornucopia2ndEditionUpgrade" or do not try to group special cards, it does work.).

**Comment by sumpfork** [comment]
#498

**Comment by sumpfork** [comment]
Replaced by #517

**Pull request closed without merging**
