### PR TITLE
Renaissance

### PR DESCRIPTION
**Pull request by wvoigt**
Just wanted to start a place where we can put all the changes.
I created the Pull Request so we have a place to make comments.  It is not ready yet.
Still needed are:
* Unannounced cards
* CI test changes to make it pass

For now, I have matched up all the Artifacts to their cards.  If other artifacts don't follow this pattern, then we will need to do something different.

### CODE REVIEW

**Comment by wvoigt** [comment]
I could use some fresh eyes proof reading these.  Attached are two sample outputs.
[renaissance-test-2.pdf](https://github.com/sumpfork/dominiontabs/files/2568005/renaissance-test-2.pdf)
[renaissance-test-1.pdf](https://github.com/sumpfork/dominiontabs/files/2568006/renaissance-test-1.pdf)

**Comment by nickv2002** [comment]
Thanks @wvoigt !
I did a quick visual look over the 2 PDFs and they seem pretty good: I didn't spot anything wrong. But more through proof-reading is obviously needed. Not sure when I'll have time for more but I'll post if I do.

**Comment by sumpfork** [comment]
I released and deployed the current master, and updated this branch with it so we can do a clean release of this PR. Should have some time to look at over the coming 2 days.

**Comment by siejai** [comment]
> I could use some fresh eyes proof reading these. Attached are two sample outputs.
> [renaissance-test-2.pdf](https://github.com/sumpfork/dominiontabs/files/2568005/renaissance-test-2.pdf)
> [renaissance-test-1.pdf](https://github.com/sumpfork/dominiontabs/files/2568006/renaissance-test-1.pdf)

The only actual issue I see is present on both test files on Hideout.

Text reads:
+1 Card

+2 Actions
Trash a card...

Should read:
+1 Card
+2 Actions

Trash a card...

------
Other than that, visually some of the text on the dividers are getting split in a way that makes them less easily readable.  When the text has a bolded +(number) (effect) they are often getting split.

On Test 1 - Acting Troupe has +4 / Villagers; Lackeys has +2 / Villagers.
Test 2 has it happening a lot more frequently due to being more narrow.
Academy: +1 / Villager ; Barracks: +1 / Action ; Crop Rotation: +2 / Cards ; Ducat: +1 / Buy; Exploration: +1 / Coffers and +1 Villager; Flag: +1 / Card; Guildhall +1 / Coffers; Recruiter +1 / Villager (also a split in Recruiter Rules); Sculptor +1 / Villager.

**Pull request merged**
