### PR TITLE
Added Dutch translations for Nocturne and Renaissance and fixed some …

### PR DESCRIPTION
**Pull request by maksler**
…typos and grammar

I wasn't able to check whether everything works ok, so if you let me know if I made some mistakes, I'll fix them right away.

### CODE REVIEW

**Comment by sumpfork** [comment]
You can see the automated build failing here: https://travis-ci.org/github/sumpfork/dominiontabs - not sure why it's not showing up here on github anymore, will need to investigate.

I recommend using a text editor that has a JSON mode to verify that the files are still valid JSON, or using some online validator like https://jsonlint.com/

**Comment by maksler** [comment]
Thanks for the reply! I feel a bit stupid I didn't even check that. I'll install a linter or use a different program to edit. That way I can also check whether I've closed all html elements.

**Comment by sumpfork** [comment]
I added #300 which fixes the JSON, but there are some tags internal to the text that are not closed. I don't have time to look at it right now, but feel free to pull that branch and work from there.

**Comment by sumpfork** [comment]
Replaced by #300, which still needs some more fixes (feel free to make another PR based on that, though.)

**Pull request closed without merging**
