### PR TITLE
Fix partial page crop-marks

### PR DESCRIPTION
**Pull request by wvoigt**
Add crop marks on partial pages. Fixes Issue #361

### CODE REVIEW

**Comment by sumpfork** [comment]
@bszonye do you have time to test this? I don't at the moment...

**Comment by bszonye** [comment]
The fix works for me, although there's one change I'd recommend if it's not too difficult to implement.

In the image, I've highlighted all of the new cropmarks added by the fix. The four marks in blue are good, but the two marks at the inside corner (highlighted in orange) overlap the diagonally adjacent card. That's not ideal, as it can leave a faint mark after cropping. If possible, it'd be better to suppress any marks originating from that inside corner.

Otherwise, LGTM. Thanks for the fix!

cropmarks

**Comment by wvoigt** [comment]
> In the image, I've highlighted all of the new cropmarks added by the fix. The four marks in blue are good, but the two marks at the inside corner (highlighted in orange) overlap the diagonally adjacent card. That's not ideal, as it can leave a faint mark after cropping. If possible, it'd be better to suppress any marks originating from that inside corner.

I see what you are saying.  However, at this time, the cropmarks are controlled by the side of the card.  So Top, Bottom, Left, Right.  It will take a bigger code change to exclude just the Right upper and the Bottom left.   I need to think through the ramifications.

**Comment by bszonye** [comment]
Cool, I wasn't sure how much hassle it would be to account for that subtlety. This is an improvement regardless. Thanks!

**Pull request merged**
