### PR TITLE
Add ability to use and save options in files

### PR DESCRIPTION
**Pull request by wvoigt**
Created a pull request to make it easier to comment/review.

### CODE REVIEW

**Comment by wvoigt** [comment]
This goes with Issue #123 

The failure seems to be the failure to load 'configargparse'.  I presume it needs to be installed.  Not sure if I can do that.

**Comment by sumpfork** [comment]
You can - it needs to be added to `requirements.in` which then needs to be compiled to `requirements.txt` using pip-tools' `pip-compile`.

**Comment by sumpfork** [comment]
Ah, sorry, I forgot. Run `doit compile_requirements` instead of `pip-compile`.

**Comment by wvoigt** [comment]
OK, I'm at a loss.  The error is:
The command "python setup.py test" exited with 1.

That said, I could not run `doit compile_requirements` on my system for some reason.   Not sure if that changes anything in the background.

**Comment by sumpfork** [comment]
Yeah, there's something still wrong with the travis setup. Master builds are failing because travis at some point checked in one of your PR branch changes into master - with a build number that doesn't exist in the travis build history. Not sure what's going on, need to find time to investigate. Has nothing to do with this PR as far as I can tell.

**Pull request merged**
