### PR TITLE
New Updates for Nocturne & Dismantle Promo

### PR DESCRIPTION
**Pull request by nickv2002**
Still needs updates with Nocturne Rules.

### CODE REVIEW

**Comment by wvoigt** [comment]
Please review the cards.   I think we have everything in now.  I added the "Extra" rules text from the rule book.

As a reminder, once everything is done with the en_us files, we will run /tools/update_language.py to pretty up all the files (e.g., alphabetize) and then add the new text to all the other language files.

**Comment by sumpfork** [comment]
I put this branch up at http://staging.sandflea.org for you to check out.

**Comment by wvoigt** [comment]
Are the treasure_nc images upside down on purpose?  I just noticed they are different.

**Comment by wvoigt** [comment]
And as a reminder, it is probably best to use the `--types` and `--count` options to verify the type and card count information too.  And with `--special_card_groups` and without it to see individual dividers as well as the grouping dividers.

**Comment by tsemerad** [comment]
I think the branch looks great! I noticed a few small things:
- the card name text of the Night cards isn't white. It's not necessarily mandatory in my opinion, but it would match how the cards themselves look. I don't know if this was considered, or is possible.
- there is no explanation text on the back of the Dismantle divider. I'm assuming that such text just doesn't exist yet for Dismantle?

I was surprised at first to not see dual colored headers for Night-Duration cards like Ghost, but then noticed that the cards themselves have just a single-colored header, so they do indeed match. I was expecting something like the Fool's Gold header that is blue and gold, but I guess if they did do orange/black headers the header text would be hard to read. Good job!

**Comment by wvoigt** [comment]
I completed my card by card review and have updated the changes.

@tsemerad I have not seen any additional explanation text for Dismantle.  http://wiki.dominionstrategy.com/index.php/Dismantle still does not have anything else on it.  As for Nocturne night white text on the dark background: I quickly looked at the code and it was not a quick change.  So unless @sumpfork says otherwise, I was concentrating on getting the cards ready as a priority.

**Comment by sumpfork** [comment]
Yes, let's get this released first, text colour tweaking can come later if at all.

Seems like some folks have checked this over (I just had a quick peek, nothing comprehensive.) Are we good to land this branch and release?

I'll do so later today unless I hear otherwise.

**Comment by wvoigt** [comment]
I have run /tools/update_language.py to:

- pretty up the _db files
- alphabetize the us_en files
- push the changes (and alphabetized) to all other languages.  So all languages will at least have the new Dividers, even if they are in English.

I think this is ready to go.

**Comment by sumpfork** [comment]
@wvoigt what are the \*/fix/\* files?

**Comment by wvoigt** [comment]
@sumpfork My screw-up.  Holdover files I that were left over from other work.  They need to be deleted.

**Comment by wvoigt** [comment]
I may have clobbered recent French changes.  I'm going to pull down a fresh copy and rerun the script.

**Comment by wvoigt** [comment]
It is a problem with the bonus text files.  The update script is just over writing them.  Since no bonus have changed, I will restore those files.

**Comment by wvoigt** [comment]
I noticed the sets_??.json files all had an extra "used" value.  Fixed  /tools/update_language.py and uploaded the new files.  Downloaded fresh language files and reran.

I *think* (hope) I have it correct now.

**Comment by wvoigt** [comment]
I'm not sure why many of the file changes are showing up as completely new files (all lines deleted, then full adds.)  I was thinking there were extra spaces or something, but after spot checking a few, I just don't see the changes.  Any ideas?

**Comment by sumpfork** [comment]
It’s likely line ending changes, I thought I fixed the git setting for that. I’ll look at it tomorrow.

**Comment by sumpfork** [comment]
I re-normalized the line endings. @wvoigt your script is resetting the translations - from a quick peek, maybe the 'untranslated' fields didn't get updated correctly? I don't have more time right now, might get to it Tuesday if nobody else does.

**Comment by wvoigt** [comment]
At a quick glance, it looks like some of the translations (mostly base cards)  for #170 in the main branch did not update the 'untranslated' field. So as is, they would be overridden.

**Comment by sumpfork** [comment]
Ok, I fixed up the french translation files, reran the language script, and redeployed the branch to staging.sandflea.org. The diff looks ok to me - let me know if you find problems, otherwise I'll land it to master ... probably on Tuesday?

And to note, I followed the instructions at https://help.github.com/articles/dealing-with-line-endings/ to deal with line endings a while ago. Maybe you need to reset your local index too, @wvoigt?

**Comment by nickv2002** [comment]
Nice work on this everyone. 👍

**Pull request merged**
