### PR TITLE
Enhancements - fulltab, center_name, back_offset_height

### PR DESCRIPTION
**Pull request by wvoigt**
Added 3 enhancements:
--fulltab to make the tab the full width of the divider
--center_name to center the card name on the tab
--back_offset_height to add points in the vertical direction on the back
page

### CODE REVIEW

**Comment by sumpfork** [comment]
Thanks, that's great.

Though I do feel that we should probably replace the various name alignment options with a single one that has several choices, "left", "edge" and "centre".

**Comment by wvoigt** [comment]
and center :-)  Any worry about backwards compatability with the options?

**Comment by sumpfork** [comment]
It looks like I haven't exposed any of them on the generator page at http://domtabs.sandflea.org, and combining them would actually make that easier. So no, no backwards compatibility problems that I can think of right now.

**Comment by wvoigt** [comment]
OK, I'll work on that.

**Pull request merged**
