### PR TITLE
Added sets for removed cards from 1st editions of Dominion and Intrigue

### PR DESCRIPTION
**Pull request by wvoigt**
This fixes Issue #359.
Adds sets for the cards that were removed from the first edition of Dominion and Intrigue.

### CODE REVIEW

**Comment by sumpfork** [comment]
Hmm, I haven't tried, but with this if no options are specified are the cards included both as standard and as removed? If so, I think we should start having some sets that are excluded when nothing is specified?

**Comment by wvoigt** [comment]
As is, it adds another set with the specific removed cards.  They also appear in the 1st edition set.  This is very similar to how the upgrade sets are printed even though they are also included in the 2nd edition sets.

That said, I agree the default prints a lot of sets & cards now. It would not be too hard to add on to the empty `options.expansions` check and add "*Removed" to the `options.exclude_expansions`.  Might make sense to have this as a constant list so it is easier to add more to it in the future if needed. Something like: 
```
DEFAULT_EXCLUDE_SETS= ["*Removed"]

...

    if options.expansions is None:
        # No instance given, so default to all Official expansions
        options.expansions = ["*"]
        # But exclude the seldom used expansions		<-- New
        if options.exclude_expansions is None:			<-- New
            options.exclude_expansions = []			<-- New
        options.exclude_expansions.append(DEFAULT_EXCLUDE_SETS)	<-- New
```
If you think this is a good idea, I can easily add it.

**Comment by sumpfork** [comment]
Yeah, I think by default as little as possible unexpected card duplication should occur, and second editions should be preferred.

**Comment by wvoigt** [comment]
Another way to do it is just change `--edition` to be 'latest' instead of 'all' when no expansions are listed. It would be simpler and have the same result.

**Comment by wvoigt** [comment]
This is what I will implement.  When no expansions are specified:

- If no `--edition` is specified, then the new default will be to print all the latest editions (no 1st editions, no upgrades, no removed cards).  Prior behavior printed everything.
- If `--edition` is specified, all editions will be filtered by the `--edition` parameter (so it over rides the above).

The prior default behavior can be done by either specifying `--expansions *`  or  `--edition=all`

To give easy options to just print upgrade cards or removed cards, I will add `upgrade` and `removed` as options to `--edition`.

**Comment by bszonye** [comment]
Thanks, this sounds great! Looking forward to trying it out.

**Pull request merged**
