### PR TITLE
feat: updated sets and translations for bigbox 2 german edition

### PR DESCRIPTION
**Pull request by despian**
A couple of cards in the German Bigbox v2 have slightly different translations.

I added 2 new sets (`promo-bigbox2-de` and `guilds-bigbox2-de`) to support the different names of the cards:

"Carcassonne" -> "Befestigtes Dorf"
"Wahrsager" -> "Hellseherin"

### CODE REVIEW

**Comment by despian** [comment]
Sorry, missed that part of the readme. Should be good now.

**Comment by sumpfork** [comment]
I don't know why travis is not reporting the outcomes of tests correctly to github anymore, but see https://travis-ci.org/github/sumpfork/dominiontabs/builds/665841935

**Comment by despian** [comment]
Yeah, I see. I wrongly assumed the pre-commit hook was running the tests and that they had passed.

I've added these new sets to the failing test. Should be passing now. (Though redefining part of the card_db in a test seems a little odd to me, not very DRY...)

I'm not really happy with the number of changes required here for this seemingly simple thing. I'm sure there are better ways of achieving this but would probably require changing the underlying structure of the generator a bit. Which I'm not really up for tbh.

I accomplished what I needed anyhow and this would help others trying to use it for the same bigbiox version I have. That said, I understand if you don't want to merge this.

**Comment by sumpfork** [comment]
Replaced by #440

**Pull request closed without merging**
