### PR TITLE
Added Captain and Church Promos

### PR DESCRIPTION
**Pull request by nickv2002**
Added Captain and Church Promos

### CODE REVIEW

**Comment by nickv2002** [comment]
Fixes https://github.com/sumpfork/dominiontabs/issues/265

**Comment by nickv2002** [comment]
Gotta work on other stuff right now. Not sure if you generally ignore all the language checks.

**Comment by sumpfork** [comment]
Thanks! Just needed to run the update_language tool.

**Comment by nickv2002** [comment]
Nice. I figured it was some script like that but didn't have time to poke around more. Thanks!

**Pull request merged**
