### PR TITLE
Some Adventure-Cards translated. I hope I got the tokens right.

### PR DESCRIPTION
**Pull request by idlaviV**
I tried to translate some cards. Not sure what to do with translation-errors on original cards.

### CODE REVIEW

**Comment by wvoigt** [comment]
Are you sure about Dungeon? The +2 Karten?

**Comment by sumpfork** [comment]
They're actually equivalent: The English just says 'now and at the start of your next turn' for the gain and discard 2 cards, whereas the German fully describes the current turn (+ 1 Action, +2 Cards, then discard 2 cards) and then describes the beginning of the next turn separately (+2 Cards, then discard 2 cards).

**Comment by sumpfork** [comment]
This can now be reparent to master, I merged `Card-DB-refactoring` into master.

**Comment by idlaviV** [comment]
I am rather new to github - do I have to reparent this? How do I do it?
I now cloned your repository instead of my forked one, but I guess I have not the rights to push changes.

**Comment by wvoigt** [comment]
I think this shows how to reparent: https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by idlaviV** [comment]
The other pull request is now much bigger. And better. Take the other one.

**Pull request closed without merging**
