### PR TITLE
Randomizer Fix

### PR DESCRIPTION
**Pull request by wvoigt**
This fixes Issue #184 
On the expansion dividers, the card count is now the number of randomizer cards for that expansion.
On the alphabetical list of cards printed on the expansion divider, regular text font is used for the cards with randomizers (as in the past), and cards without randomizers are displayed in _italics_.

In addition to helping keep track of randomizers, this also makes sure the expansion slip covers are the right size to hold the randomizers.

### CODE REVIEW

**Comment by wvoigt** [comment]
I'm having trouble with the new CI checks.  It does not like the new
` "randomizer": false, `
entries in the `cards_db.json` file.

**Comment by sumpfork** [comment]
You should be able to run it locally using `py.test` for easier checking.

What that test does is run your language update script, then run a diff on what it generates and what is in the `card_db` dir in `domdiv` to make sure there are no differences. Looks like maybe the lines are being reshuffled? Just run the language update tool first and check its output in if it looks ok.

**Comment by wvoigt** [comment]
@sumpfork 
The only thing that changed was adding 
`"randomizer": false, `
to some entries in the `cards_db.json` file.  
Nothing that should have changed anything with the languages files.  And I didn't reorder any cards in the db.  Interesting.

**Comment by sumpfork** [comment]
I'm saying the update language script is probably reordering the fields from the order you checked in. Just check in what it generates.

**Pull request closed without merging**
